### PR TITLE
Add server side encryption and `Content-Type` support.

### LINKED ISSUE #16: Add Server Side Encryption support
s3-stream at the moment does not support SSE (Server Side Encryption) would be good to add it. We need it in our side.

### PR DESCRIPTION
**Pull request by filosganga**
This PR fixes #16 and #2. It introduces the `Metadata` class to hold information about the content type and server side encryption.

It also models the server side encryption AWS headers.

### CODE REVIEW

**Comment by filosganga** [comment]
@joearasin This PR has been updated with KMS context. I make it with string interpolation and JSON parser combinator.

**Comment by hderms** [comment]
@joearasin this would be awesome if we could get this merged in

**Comment by joearasin** [comment]
I need to update the readme, but this repo is deprecated -- This project has been merged into Alpakka: https://github.com/akka/alpakka/

**Comment by filosganga** [comment]
@hderms I will reopen against the alpakka when I will have the time, so bad we did not manage to merge before.

**Pull request closed without merging**
